#!/bin/bash

#create a random string for temporary use
TMPBRANCH=`echo $RAMDOM$RANDOM$RANDOM$RANDOM$RANDOM | base64 | tr -d \\n\=`

# check for a valid git repo
if [ ! -d .git ]; then
	echo "This does not appear to be the root directory of a valid git repository";
	exit;
fi;

# create the proper directory structure in EMPTY svn repo
# make sure the repo is completely new, else this probably won't work
mkdir /tmp/$TMPBRANCH
cd /tmp/$TMPBRANCH
mkdir trunk branches tags
svn import . $1 -m "Created svn repository structure" || exit; 

#change back to our git repo
cd -

# create an empty root commit to rebase the master upon
git symbolic-ref HEAD refs/heads/$TMPBRANCH
git rm --cached -r .
git clean -f -d
git commit --allow-empty -m 'Empty Commit'
git cherry-pick $(git rev-list --reverse master | head -1)
git rebase --onto $TMPBRANCH $TMPBRANCH master
git branch -d $TMPBRANCH

#import the empty svn repo into git
git svn init --prefix=svn/ $1 --branches=branches --trunk=trunk --tags=tags .
git svn fetch

#create a temporary branch
git checkout -b $TMPBRANCH svn/trunk
#rebase our master branch on this temp branch
git rebase --onto $TMPBRANCH $TMPBRANCH master
#delete the temp branch
git branch -D $TMPBRANCH
#push out the commits to svn
git svn dcommit

